# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
#  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Zeroaan's blog
subtitle: Python Coding
email: yj6210ag@gmail.com
name: Jinyoung Ahn
description: >
  Jinyoung's coding blog  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zeroaan.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
inter_post_navigation: true
highlightjs_theme: "monokai-sublime"
paginate: 10
paginate_path: "/page:num/"

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
#pagination:
#  enabled: true
#  debug: false
#  collection: "posts"
#  per_page: 10
#  permalink: "/page/:num/"
#  limit: 0
#  sort_reverse: true

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
#jekyll-archives:
#  enabled:
#    - categories
#    - tags
#  layout: 'archive'
#  permalinks:
#    category: '/category/:name/'
#    tag: '/tag/:name/'

# Disqus comments
#disqus_shortname: zeroaan
#disqus_url: https://zeroaan.disqus.com/
#disqus_id: zeroaan

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
#descriptions:
#  - cat: jekyll
#    desc: "Posts describing Jekyll setup techniques."

#  - cat: dummy
#    desc: "Just some placeholder posts, lorem ipsum and the rest."

#  - cat: python
#    desc: "Python coding."
# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: GitHub
    icon: github
    username: zeroaan
    url: https://github.com/zeroaan
    desc: Fork me on GitHub
    share: false

  - name: Google
    icon: google-plus
    username: ""
    url: ""
    desc: Share to goole
    share: true

#  - name: Google+
#    icon: google-plus
#    username: ""
#    url: ""
#    desc: Add me to your Circles
#    share: true

#  - name: YouTube
#    icon: youtube
#    username: ""
#    url: ""
#    desc: Subscribe on YouTube
#    share: false

#  - name: Instagram
#    icon: instagram
#    username: ""
#    url: ""
#    desc: Follow me on Instagram
#    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
